local LSM = LibStub("LibSharedMedia-3.0") 

-- ----- 
-- BACKGROUND 
-- ----- 

-- ----- 
--  BORDER 
-- ---- 

-- -----
--   FONT
-- -----

-- -----
--   SOUND
-- -----
LSM:Register("sound", "Blip_Select", [[Interface\Addons\SharedMedia_MyMedia\sound\Blip_Select.ogg]]) 
LSM:Register("sound", "Blip_Select10", [[Interface\Addons\SharedMedia_MyMedia\sound\Blip_Select10.ogg]]) 
LSM:Register("sound", "Blip_Select11", [[Interface\Addons\SharedMedia_MyMedia\sound\Blip_Select11.ogg]]) 
LSM:Register("sound", "Blip_Select12", [[Interface\Addons\SharedMedia_MyMedia\sound\Blip_Select12.ogg]]) 
LSM:Register("sound", "Blip_Select13", [[Interface\Addons\SharedMedia_MyMedia\sound\Blip_Select13.ogg]]) 
LSM:Register("sound", "Blip_Select14", [[Interface\Addons\SharedMedia_MyMedia\sound\Blip_Select14.ogg]]) 
LSM:Register("sound", "Blip_Select15", [[Interface\Addons\SharedMedia_MyMedia\sound\Blip_Select15.ogg]]) 
LSM:Register("sound", "Blip_Select16", [[Interface\Addons\SharedMedia_MyMedia\sound\Blip_Select16.ogg]]) 
LSM:Register("sound", "Blip_Select17", [[Interface\Addons\SharedMedia_MyMedia\sound\Blip_Select17.ogg]]) 
LSM:Register("sound", "Blip_Select18", [[Interface\Addons\SharedMedia_MyMedia\sound\Blip_Select18.ogg]]) 
LSM:Register("sound", "Blip_Select19", [[Interface\Addons\SharedMedia_MyMedia\sound\Blip_Select19.ogg]]) 
LSM:Register("sound", "Blip_Select2", [[Interface\Addons\SharedMedia_MyMedia\sound\Blip_Select2.ogg]]) 
LSM:Register("sound", "Blip_Select20", [[Interface\Addons\SharedMedia_MyMedia\sound\Blip_Select20.ogg]]) 
LSM:Register("sound", "Blip_Select3", [[Interface\Addons\SharedMedia_MyMedia\sound\Blip_Select3.ogg]]) 
LSM:Register("sound", "Blip_Select4", [[Interface\Addons\SharedMedia_MyMedia\sound\Blip_Select4.ogg]]) 
LSM:Register("sound", "Blip_Select5", [[Interface\Addons\SharedMedia_MyMedia\sound\Blip_Select5.ogg]]) 
LSM:Register("sound", "Blip_Select6", [[Interface\Addons\SharedMedia_MyMedia\sound\Blip_Select6.ogg]]) 
LSM:Register("sound", "Blip_Select7", [[Interface\Addons\SharedMedia_MyMedia\sound\Blip_Select7.ogg]]) 
LSM:Register("sound", "Blip_Select8", [[Interface\Addons\SharedMedia_MyMedia\sound\Blip_Select8.ogg]]) 
LSM:Register("sound", "Blip_Select9", [[Interface\Addons\SharedMedia_MyMedia\sound\Blip_Select9.ogg]]) 
LSM:Register("sound", "Default", [[Interface\Addons\SharedMedia_MyMedia\sound\Default.ogg]]) 
LSM:Register("sound", "Explosion", [[Interface\Addons\SharedMedia_MyMedia\sound\Explosion.ogg]]) 
LSM:Register("sound", "Explosion10", [[Interface\Addons\SharedMedia_MyMedia\sound\Explosion10.ogg]]) 
LSM:Register("sound", "Explosion11", [[Interface\Addons\SharedMedia_MyMedia\sound\Explosion11.ogg]]) 
LSM:Register("sound", "Explosion12", [[Interface\Addons\SharedMedia_MyMedia\sound\Explosion12.ogg]]) 
LSM:Register("sound", "Explosion13", [[Interface\Addons\SharedMedia_MyMedia\sound\Explosion13.ogg]]) 
LSM:Register("sound", "Explosion14", [[Interface\Addons\SharedMedia_MyMedia\sound\Explosion14.ogg]]) 
LSM:Register("sound", "Explosion15", [[Interface\Addons\SharedMedia_MyMedia\sound\Explosion15.ogg]]) 
LSM:Register("sound", "Explosion16", [[Interface\Addons\SharedMedia_MyMedia\sound\Explosion16.ogg]]) 
LSM:Register("sound", "Explosion17", [[Interface\Addons\SharedMedia_MyMedia\sound\Explosion17.ogg]]) 
LSM:Register("sound", "Explosion18", [[Interface\Addons\SharedMedia_MyMedia\sound\Explosion18.ogg]]) 
LSM:Register("sound", "Explosion19", [[Interface\Addons\SharedMedia_MyMedia\sound\Explosion19.ogg]]) 
LSM:Register("sound", "Explosion2", [[Interface\Addons\SharedMedia_MyMedia\sound\Explosion2.ogg]]) 
LSM:Register("sound", "Explosion20", [[Interface\Addons\SharedMedia_MyMedia\sound\Explosion20.ogg]]) 
LSM:Register("sound", "Explosion3", [[Interface\Addons\SharedMedia_MyMedia\sound\Explosion3.ogg]]) 
LSM:Register("sound", "Explosion4", [[Interface\Addons\SharedMedia_MyMedia\sound\Explosion4.ogg]]) 
LSM:Register("sound", "Explosion5", [[Interface\Addons\SharedMedia_MyMedia\sound\Explosion5.ogg]]) 
LSM:Register("sound", "Explosion6", [[Interface\Addons\SharedMedia_MyMedia\sound\Explosion6.ogg]]) 
LSM:Register("sound", "Explosion7", [[Interface\Addons\SharedMedia_MyMedia\sound\Explosion7.ogg]]) 
LSM:Register("sound", "Explosion8", [[Interface\Addons\SharedMedia_MyMedia\sound\Explosion8.ogg]]) 
LSM:Register("sound", "Explosion9", [[Interface\Addons\SharedMedia_MyMedia\sound\Explosion9.ogg]]) 
LSM:Register("sound", "Jump", [[Interface\Addons\SharedMedia_MyMedia\sound\Jump.ogg]]) 
LSM:Register("sound", "Jump10", [[Interface\Addons\SharedMedia_MyMedia\sound\Jump10.ogg]]) 
LSM:Register("sound", "Jump11", [[Interface\Addons\SharedMedia_MyMedia\sound\Jump11.ogg]]) 
LSM:Register("sound", "Jump12", [[Interface\Addons\SharedMedia_MyMedia\sound\Jump12.ogg]]) 
LSM:Register("sound", "Jump13", [[Interface\Addons\SharedMedia_MyMedia\sound\Jump13.ogg]]) 
LSM:Register("sound", "Jump14", [[Interface\Addons\SharedMedia_MyMedia\sound\Jump14.ogg]]) 
LSM:Register("sound", "Jump15", [[Interface\Addons\SharedMedia_MyMedia\sound\Jump15.ogg]]) 
LSM:Register("sound", "Jump16", [[Interface\Addons\SharedMedia_MyMedia\sound\Jump16.ogg]]) 
LSM:Register("sound", "Jump17", [[Interface\Addons\SharedMedia_MyMedia\sound\Jump17.ogg]]) 
LSM:Register("sound", "Jump18", [[Interface\Addons\SharedMedia_MyMedia\sound\Jump18.ogg]]) 
LSM:Register("sound", "Jump19", [[Interface\Addons\SharedMedia_MyMedia\sound\Jump19.ogg]]) 
LSM:Register("sound", "Jump2", [[Interface\Addons\SharedMedia_MyMedia\sound\Jump2.ogg]]) 
LSM:Register("sound", "Jump20", [[Interface\Addons\SharedMedia_MyMedia\sound\Jump20.ogg]]) 
LSM:Register("sound", "Jump3", [[Interface\Addons\SharedMedia_MyMedia\sound\Jump3.ogg]]) 
LSM:Register("sound", "Jump4", [[Interface\Addons\SharedMedia_MyMedia\sound\Jump4.ogg]]) 
LSM:Register("sound", "Jump5", [[Interface\Addons\SharedMedia_MyMedia\sound\Jump5.ogg]]) 
LSM:Register("sound", "Jump6", [[Interface\Addons\SharedMedia_MyMedia\sound\Jump6.ogg]]) 
LSM:Register("sound", "Jump7", [[Interface\Addons\SharedMedia_MyMedia\sound\Jump7.ogg]]) 
LSM:Register("sound", "Jump8", [[Interface\Addons\SharedMedia_MyMedia\sound\Jump8.ogg]]) 
LSM:Register("sound", "Jump9", [[Interface\Addons\SharedMedia_MyMedia\sound\Jump9.ogg]]) 
LSM:Register("sound", "Laser_Shoot", [[Interface\Addons\SharedMedia_MyMedia\sound\Laser_Shoot.ogg]]) 
LSM:Register("sound", "Laser_Shoot10", [[Interface\Addons\SharedMedia_MyMedia\sound\Laser_Shoot10.ogg]]) 
LSM:Register("sound", "Laser_Shoot11", [[Interface\Addons\SharedMedia_MyMedia\sound\Laser_Shoot11.ogg]]) 
LSM:Register("sound", "Laser_Shoot12", [[Interface\Addons\SharedMedia_MyMedia\sound\Laser_Shoot12.ogg]]) 
LSM:Register("sound", "Laser_Shoot13", [[Interface\Addons\SharedMedia_MyMedia\sound\Laser_Shoot13.ogg]]) 
LSM:Register("sound", "Laser_Shoot14", [[Interface\Addons\SharedMedia_MyMedia\sound\Laser_Shoot14.ogg]]) 
LSM:Register("sound", "Laser_Shoot15", [[Interface\Addons\SharedMedia_MyMedia\sound\Laser_Shoot15.ogg]]) 
LSM:Register("sound", "Laser_Shoot16", [[Interface\Addons\SharedMedia_MyMedia\sound\Laser_Shoot16.ogg]]) 
LSM:Register("sound", "Laser_Shoot17", [[Interface\Addons\SharedMedia_MyMedia\sound\Laser_Shoot17.ogg]]) 
LSM:Register("sound", "Laser_Shoot18", [[Interface\Addons\SharedMedia_MyMedia\sound\Laser_Shoot18.ogg]]) 
LSM:Register("sound", "Laser_Shoot19", [[Interface\Addons\SharedMedia_MyMedia\sound\Laser_Shoot19.ogg]]) 
LSM:Register("sound", "Laser_Shoot2", [[Interface\Addons\SharedMedia_MyMedia\sound\Laser_Shoot2.ogg]]) 
LSM:Register("sound", "Laser_Shoot20", [[Interface\Addons\SharedMedia_MyMedia\sound\Laser_Shoot20.ogg]]) 
LSM:Register("sound", "Laser_Shoot3", [[Interface\Addons\SharedMedia_MyMedia\sound\Laser_Shoot3.ogg]]) 
LSM:Register("sound", "Laser_Shoot4", [[Interface\Addons\SharedMedia_MyMedia\sound\Laser_Shoot4.ogg]]) 
LSM:Register("sound", "Laser_Shoot5", [[Interface\Addons\SharedMedia_MyMedia\sound\Laser_Shoot5.ogg]]) 
LSM:Register("sound", "Laser_Shoot6", [[Interface\Addons\SharedMedia_MyMedia\sound\Laser_Shoot6.ogg]]) 
LSM:Register("sound", "Laser_Shoot7", [[Interface\Addons\SharedMedia_MyMedia\sound\Laser_Shoot7.ogg]]) 
LSM:Register("sound", "Laser_Shoot8", [[Interface\Addons\SharedMedia_MyMedia\sound\Laser_Shoot8.ogg]]) 
LSM:Register("sound", "Laser_Shoot9", [[Interface\Addons\SharedMedia_MyMedia\sound\Laser_Shoot9.ogg]]) 
LSM:Register("sound", "Pickup_Coin", [[Interface\Addons\SharedMedia_MyMedia\sound\Pickup_Coin.ogg]]) 
LSM:Register("sound", "Pickup_Coin10", [[Interface\Addons\SharedMedia_MyMedia\sound\Pickup_Coin10.ogg]]) 
LSM:Register("sound", "Pickup_Coin11", [[Interface\Addons\SharedMedia_MyMedia\sound\Pickup_Coin11.ogg]]) 
LSM:Register("sound", "Pickup_Coin12", [[Interface\Addons\SharedMedia_MyMedia\sound\Pickup_Coin12.ogg]]) 
LSM:Register("sound", "Pickup_Coin13", [[Interface\Addons\SharedMedia_MyMedia\sound\Pickup_Coin13.ogg]]) 
LSM:Register("sound", "Pickup_Coin14", [[Interface\Addons\SharedMedia_MyMedia\sound\Pickup_Coin14.ogg]]) 
LSM:Register("sound", "Pickup_Coin15", [[Interface\Addons\SharedMedia_MyMedia\sound\Pickup_Coin15.ogg]]) 
LSM:Register("sound", "Pickup_Coin16", [[Interface\Addons\SharedMedia_MyMedia\sound\Pickup_Coin16.ogg]]) 
LSM:Register("sound", "Pickup_Coin17", [[Interface\Addons\SharedMedia_MyMedia\sound\Pickup_Coin17.ogg]]) 
LSM:Register("sound", "Pickup_Coin18", [[Interface\Addons\SharedMedia_MyMedia\sound\Pickup_Coin18.ogg]]) 
LSM:Register("sound", "Pickup_Coin19", [[Interface\Addons\SharedMedia_MyMedia\sound\Pickup_Coin19.ogg]]) 
LSM:Register("sound", "Pickup_Coin2", [[Interface\Addons\SharedMedia_MyMedia\sound\Pickup_Coin2.ogg]]) 
LSM:Register("sound", "Pickup_Coin20", [[Interface\Addons\SharedMedia_MyMedia\sound\Pickup_Coin20.ogg]]) 
LSM:Register("sound", "Pickup_Coin3", [[Interface\Addons\SharedMedia_MyMedia\sound\Pickup_Coin3.ogg]]) 
LSM:Register("sound", "Pickup_Coin4", [[Interface\Addons\SharedMedia_MyMedia\sound\Pickup_Coin4.ogg]]) 
LSM:Register("sound", "Pickup_Coin5", [[Interface\Addons\SharedMedia_MyMedia\sound\Pickup_Coin5.ogg]]) 
LSM:Register("sound", "Pickup_Coin6", [[Interface\Addons\SharedMedia_MyMedia\sound\Pickup_Coin6.ogg]]) 
LSM:Register("sound", "Pickup_Coin7", [[Interface\Addons\SharedMedia_MyMedia\sound\Pickup_Coin7.ogg]]) 
LSM:Register("sound", "Pickup_Coin8", [[Interface\Addons\SharedMedia_MyMedia\sound\Pickup_Coin8.ogg]]) 
LSM:Register("sound", "Pickup_Coin9", [[Interface\Addons\SharedMedia_MyMedia\sound\Pickup_Coin9.ogg]]) 
LSM:Register("sound", "Powerup", [[Interface\Addons\SharedMedia_MyMedia\sound\Powerup.ogg]]) 
LSM:Register("sound", "Powerup10", [[Interface\Addons\SharedMedia_MyMedia\sound\Powerup10.ogg]]) 
LSM:Register("sound", "Powerup11", [[Interface\Addons\SharedMedia_MyMedia\sound\Powerup11.ogg]]) 
LSM:Register("sound", "Powerup12", [[Interface\Addons\SharedMedia_MyMedia\sound\Powerup12.ogg]]) 
LSM:Register("sound", "Powerup13", [[Interface\Addons\SharedMedia_MyMedia\sound\Powerup13.ogg]]) 
LSM:Register("sound", "Powerup14", [[Interface\Addons\SharedMedia_MyMedia\sound\Powerup14.ogg]]) 
LSM:Register("sound", "Powerup15", [[Interface\Addons\SharedMedia_MyMedia\sound\Powerup15.ogg]]) 
LSM:Register("sound", "Powerup16", [[Interface\Addons\SharedMedia_MyMedia\sound\Powerup16.ogg]]) 
LSM:Register("sound", "Powerup17", [[Interface\Addons\SharedMedia_MyMedia\sound\Powerup17.ogg]]) 
LSM:Register("sound", "Powerup18", [[Interface\Addons\SharedMedia_MyMedia\sound\Powerup18.ogg]]) 
LSM:Register("sound", "Powerup19", [[Interface\Addons\SharedMedia_MyMedia\sound\Powerup19.ogg]]) 
LSM:Register("sound", "Powerup2", [[Interface\Addons\SharedMedia_MyMedia\sound\Powerup2.ogg]]) 
LSM:Register("sound", "Powerup20", [[Interface\Addons\SharedMedia_MyMedia\sound\Powerup20.ogg]]) 
LSM:Register("sound", "Powerup3", [[Interface\Addons\SharedMedia_MyMedia\sound\Powerup3.ogg]]) 
LSM:Register("sound", "Powerup4", [[Interface\Addons\SharedMedia_MyMedia\sound\Powerup4.ogg]]) 
LSM:Register("sound", "Powerup5", [[Interface\Addons\SharedMedia_MyMedia\sound\Powerup5.ogg]]) 
LSM:Register("sound", "Powerup6", [[Interface\Addons\SharedMedia_MyMedia\sound\Powerup6.ogg]]) 
LSM:Register("sound", "Powerup7", [[Interface\Addons\SharedMedia_MyMedia\sound\Powerup7.ogg]]) 
LSM:Register("sound", "Powerup8", [[Interface\Addons\SharedMedia_MyMedia\sound\Powerup8.ogg]]) 
LSM:Register("sound", "Powerup9", [[Interface\Addons\SharedMedia_MyMedia\sound\Powerup9.ogg]]) 
LSM:Register("sound", "Randomize", [[Interface\Addons\SharedMedia_MyMedia\sound\Randomize.ogg]]) 
LSM:Register("sound", "Randomize10", [[Interface\Addons\SharedMedia_MyMedia\sound\Randomize10.ogg]]) 
LSM:Register("sound", "Randomize11", [[Interface\Addons\SharedMedia_MyMedia\sound\Randomize11.ogg]]) 
LSM:Register("sound", "Randomize12", [[Interface\Addons\SharedMedia_MyMedia\sound\Randomize12.ogg]]) 
LSM:Register("sound", "Randomize13", [[Interface\Addons\SharedMedia_MyMedia\sound\Randomize13.ogg]]) 
LSM:Register("sound", "Randomize14", [[Interface\Addons\SharedMedia_MyMedia\sound\Randomize14.ogg]]) 
LSM:Register("sound", "Randomize15", [[Interface\Addons\SharedMedia_MyMedia\sound\Randomize15.ogg]]) 
LSM:Register("sound", "Randomize16", [[Interface\Addons\SharedMedia_MyMedia\sound\Randomize16.ogg]]) 
LSM:Register("sound", "Randomize17", [[Interface\Addons\SharedMedia_MyMedia\sound\Randomize17.ogg]]) 
LSM:Register("sound", "Randomize18", [[Interface\Addons\SharedMedia_MyMedia\sound\Randomize18.ogg]]) 
LSM:Register("sound", "Randomize19", [[Interface\Addons\SharedMedia_MyMedia\sound\Randomize19.ogg]]) 
LSM:Register("sound", "Randomize2", [[Interface\Addons\SharedMedia_MyMedia\sound\Randomize2.ogg]]) 
LSM:Register("sound", "Randomize20", [[Interface\Addons\SharedMedia_MyMedia\sound\Randomize20.ogg]]) 
LSM:Register("sound", "Randomize3", [[Interface\Addons\SharedMedia_MyMedia\sound\Randomize3.ogg]]) 
LSM:Register("sound", "Randomize4", [[Interface\Addons\SharedMedia_MyMedia\sound\Randomize4.ogg]]) 
LSM:Register("sound", "Randomize5", [[Interface\Addons\SharedMedia_MyMedia\sound\Randomize5.ogg]]) 
LSM:Register("sound", "Randomize6", [[Interface\Addons\SharedMedia_MyMedia\sound\Randomize6.ogg]]) 
LSM:Register("sound", "Randomize7", [[Interface\Addons\SharedMedia_MyMedia\sound\Randomize7.ogg]]) 
LSM:Register("sound", "Randomize8", [[Interface\Addons\SharedMedia_MyMedia\sound\Randomize8.ogg]]) 
LSM:Register("sound", "Randomize9", [[Interface\Addons\SharedMedia_MyMedia\sound\Randomize9.ogg]]) 

-- -----
--   STATUSBAR
-- -----
